<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f7f6; margin: 0; padding: 20px; }
        .container { background-color: #ffffff; padding: 40px; max-width: 600px; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
        .logo-container { text-align: center; margin-bottom: 30px; }
        .logo { max-width: 200px; height: auto; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h2 { color: #dc2626; margin: 0; font-size: 24px; font-weight: 600; }
        .content p { font-size: 16px; margin: 0 0 15px; }
        .details { background: #fff5f5; padding: 20px; border-radius: 6px; border-left: 4px solid #dc2626; margin-bottom: 25px; }
        .details-row { margin-bottom: 10px; font-size: 15px; }
        .details-label { font-weight: bold; color: #555; display: inline-block; width: 120px; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #777; font-size: 13px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo-container">
            <img src="<?php echo e(asset('images/logo.png')); ?>" alt="Radiance Dentistry Logo" class="logo">
        </div>

        <div class="header">
            <h2>Appointment Cancelled</h2>
        </div>

        <div class="content">
            <p>Hello Doctor,</p>

            <p>The following appointment has been <strong>cancelled</strong> and has been removed from the active schedule:</p>

            <div class="details">
                <div class="details-row"><span class="details-label">Patient Name:</span> <?php echo e($appointment->name); ?></div>
                <div class="details-row"><span class="details-label">Email:</span> <?php echo e($appointment->email); ?></div>
                <div class="details-row"><span class="details-label">Phone:</span> <?php echo e($appointment->phone); ?></div>
                <div class="details-row"><span class="details-label">Date:</span> <?php echo e($appointment->appointment_date->format('l, F j, Y')); ?></div>
                <div class="details-row"><span class="details-label">Time:</span> <?php echo e($appointment->appointment_time); ?></div>
                <div class="details-row"><span class="details-label">Reason:</span> <?php echo e($appointment->reason ?? 'Checkup'); ?></div>
            </div>

            <p>The patient has been notified of the cancellation via email. No further action is required.</p>
        </div>

        <div class="footer">
            <p>System Notification generated by Radiance Dentistry</p>
        </div>
    </div>
</body>
</html>
<?php /**PATH /var/www/html/resources/views/emails/appointments/cancelled_doctor.blade.php ENDPATH**/ ?>