<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f7f6; margin: 0; padding: 20px; }
        .container { background-color: #ffffff; padding: 40px; max-width: 600px; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
        .logo-container { text-align: center; margin-bottom: 30px; }
        .logo { max-width: 200px; height: auto; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h2 { color: #f59e0b; margin: 0; font-size: 24px; font-weight: 600; }
        .content { margin-bottom: 30px; }
        .content p { font-size: 16px; margin: 0 0 15px; }
        .details { background: #fffbeb; padding: 20px; border-radius: 6px; border-left: 4px solid #f59e0b; margin-bottom: 25px; }
        .details-row { margin-bottom: 10px; font-size: 15px; }
        .details-label { font-weight: bold; color: #555; display: inline-block; width: 120px; }
        .actions { text-align: center; margin-top: 30px; margin-bottom: 30px; }
        .btn { display: inline-block; padding: 12px 24px; margin: 0 10px 10px 0; color: #ffffff !important; text-decoration: none; border-radius: 6px; font-weight: 600; text-align: center; }
        .btn-confirm { background-color: #10b981; }
        .btn-cancel { background-color: #ef4444; }
        .btn-view { background-color: #3b82f6; display: block; margin: 20px auto 0; width: fit-content; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #777; font-size: 13px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo-container">
            <img src="{{ asset('images/logo.png') }}" alt="Radiance Dentistry Logo" class="logo">
        </div>
        
        <div class="header">
            <h2>Action Required: New Appointment</h2>
        </div>
        
        <div class="content">
            <p>Hello Doctor,</p>
            
            <p>A new appointment has been requested through the public portal and requires your confirmation before it becomes active in the system.</p>
            
            <div class="details">
                <div class="details-row"><span class="details-label">Patient Name:</span> {{ $appointment->name }}</div>
                <div class="details-row"><span class="details-label">Email:</span> {{ $appointment->email }}</div>
                <div class="details-row"><span class="details-label">Phone:</span> {{ $appointment->phone }}</div>
                <div class="details-row"><span class="details-label">Date:</span> {{ $appointment->appointment_date->format('l, F j, Y') }}</div>
                <div class="details-row"><span class="details-label">Time:</span> {{ $appointment->appointment_time }}</div>
                <div class="details-row"><span class="details-label">Reason:</span> {{ $appointment->reason ?? 'None provided' }}</div>
                @if($appointment->doctor)<div class="details-row"><span class="details-label">Doctor:</span> {{ $appointment->doctor->name }}</div>@endif
            </div>

            <p style="text-align: center; font-weight: 600; color: #444;">Please select an action below:</p>

            <div class="actions">
                <a href="{{ \Illuminate\Support\Facades\URL::signedRoute('appointment.confirm', ['appointment' => $appointment->id]) }}" class="btn btn-confirm">Confirm Appointment</a>
                <a href="{{ \Illuminate\Support\Facades\URL::signedRoute('appointment.cancel', ['appointment' => $appointment->id]) }}" class="btn btn-cancel">Cancel Appointment</a>
            </div>
            
            <p style="text-align: center; margin-top: 20px; font-size: 14px; color: #666;">Or view full details in your admin panel:</p>
            <a href="{{ url('/appointments/' . $appointment->id . '/edit') }}" class="btn btn-view">Open in Dashboard</a>
        </div>

        <div class="footer">
            <p>System Notification generated by Radiance Dentistry</p>
        </div>
    </div>
</body>
</html>
