<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f7f6; margin: 0; padding: 20px; }
        .container { background-color: #ffffff; padding: 40px; max-width: 600px; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
        .logo-container { text-align: center; margin-bottom: 30px; }
        .logo { max-width: 200px; height: auto; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h2 { color: #0284c7; margin: 0; font-size: 24px; font-weight: 600; }
        .content { margin-bottom: 30px; }
        .content p { font-size: 16px; margin: 0 0 15px; }
        .details { background: #f0f9ff; padding: 20px; border-radius: 6px; border-left: 4px solid #0284c7; margin-bottom: 25px; }
        .details-row { margin-bottom: 10px; font-size: 15px; }
        .details-label { font-weight: bold; color: #555; display: inline-block; width: 120px; }
        .btn-view { display: block; margin: 20px auto 0; width: fit-content; padding: 12px 24px; color: #ffffff !important; background-color: #0ea5e9; text-decoration: none; border-radius: 6px; font-weight: 600; text-align: center; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #777; font-size: 13px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo-container">
            <img src="{{ asset('images/logo.png') }}" alt="Radiance Dentistry Logo" class="logo">
        </div>
        
        <div class="header">
            <h2>Appointment Confirmed Successfully</h2>
        </div>
        
        <div class="content">
            <p>Hello Doctor,</p>
            
            <p>You have successfully approved this appointment in the system. The following patient is now officially active and expected on the schedule:</p>
            
            <div class="details">
                <div class="details-row"><span class="details-label">Patient Name:</span> {{ $appointment->name }}</div>
                <div class="details-row"><span class="details-label">Phone:</span> {{ $appointment->phone }}</div>
                <div class="details-row"><span class="details-label">Email:</span> {{ $appointment->email }}</div>
                <div class="details-row"><span class="details-label">Date:</span> {{ $appointment->appointment_date->format('l, F j, Y') }}</div>
                <div class="details-row"><span class="details-label">Time:</span> {{ $appointment->appointment_time }}</div>
                <div class="details-row"><span class="details-label">Reason:</span> {{ $appointment->reason ?? 'Checkup' }}</div>
                @if($appointment->doctor)<div class="details-row"><span class="details-label">Doctor:</span> {{ $appointment->doctor->name }}</div>@endif
            </div>

            @include('emails.partials.clinic_info')

            <p style="text-align: center; margin-top: 20px; font-size: 14px; color: #666;">View this record in your dashboard:</p>
            <a href="{{ url('/admin/appointments/' . $appointment->id) }}" class="btn-view">View Appointment</a>
        </div>

        <div class="footer">
            <p>System Notification generated by Radiance Dentistry</p>
        </div>
    </div>
</body>
</html>
